name: deploy to netlify

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install mdBook
        uses: extractions/setup-crate@v1
        with:
          owner: rust-lang
          name: mdBook

      - name: Generate static content for the book
        run: mdbook build

      - name: Deploy static content to netlify
        run: npx netlify-cli deploy --dir=./book
        env:
            NETLIFY_AUTH_TOKEN: "ky11tGBMLWrwTCo08GuObK_EAw0JcS8qjAy5gbZcqQ0"
            NETLIFY_SITE_ID: "dd774222-6a96-4b3a-9ba6-de4083964987"
