name: deploy to netlify

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/build

      - uses: actions/checkout@master
      - name: Publish
        run: npx netlify-cli deploy --dir=./book
        env:
            NETLIFY_AUTH_TOKEN: "ky11tGBMLWrwTCo08GuObK_EAw0JcS8qjAy5gbZcqQ0"
            NETLIFY_SITE_ID: "dd774222-6a96-4b3a-9ba6-de4083964987"
