name: deploy to netlify

on:
  push:
    branches:
    - develop
    paths:
    - "src/**.md"
    - "book.toml"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/build

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: Publish
      uses: netlify/actions/cli@develop
      with:
        args: deploy --dir=./book --prod
        secrets: '["ky11tGBMLWrwTCo08GuObK_EAw0JcS8qjAy5gbZcqQ0", "dd774222-6a96-4b3a-9ba6-de4083964987"]'
